compile:
	gcc -o addPolarizableGold addPolarizableGold.c -lm -Wall
run:
	./addPolarizableGold finalStructure_c5d1.lammps05 Au100_cut.lammpstrj c5d1gold100.data c5d1gold100.xyz
	./addPolarizableGold finalStructure_c5d1.lammps05 Au110_cut.lammpstrj c5d1gold110.data c5d1gold110.xyz
	./addPolarizableGold finalStructure_c5d1.lammps05 Au111_cut.lammpstrj c5d1gold111.data c5d1gold111.xyz
	./addPolarizableGold finalStructure_c10d1.lammps05 Au100_cut.lammpstrj c10d1gold100.data c10d1gold100.xyz
	./addPolarizableGold finalStructure_c10d1.lammps05 Au110_cut.lammpstrj c10d1gold110.data c10d1gold110.xyz
	./addPolarizableGold finalStructure_c10d1.lammps05 Au111_cut.lammpstrj c10d1gold111.data c10d1gold111.xyz
	./addPolarizableGold finalStructure_c15d1.lammps05 Au100_cut.lammpstrj c15d1gold100.data c15d1gold100.xyz
	./addPolarizableGold finalStructure_c15d1.lammps05 Au110_cut.lammpstrj c15d1gold110.data c15d1gold110.xyz
	./addPolarizableGold finalStructure_c15d1.lammps05 Au111_cut.lammpstrj c15d1gold111.data c15d1gold111.xyz
	./addPolarizableGold finalStructure_c20d1.lammps05 Au100_cut.lammpstrj c20d1gold100.data c20d1gold100.xyz
	./addPolarizableGold finalStructure_c20d1.lammps05 Au110_cut.lammpstrj c20d1gold110.data c20d1gold110.xyz
	./addPolarizableGold finalStructure_c20d1.lammps05 Au111_cut.lammpstrj c20d1gold111.data c20d1gold111.xyz
	./addPolarizableGold finalStructure_c25d1.lammps05 Au100_cut.lammpstrj c25d1gold100.data c25d1gold100.xyz
	./addPolarizableGold finalStructure_c25d1.lammps05 Au110_cut.lammpstrj c25d1gold110.data c25d1gold110.xyz
	./addPolarizableGold finalStructure_c25d1.lammps05 Au111_cut.lammpstrj c25d1gold111.data c25d1gold111.xyz
	./addPolarizableGold finalStructure_c30d1.lammps05 Au100_cut.lammpstrj c30d1gold100.data c30d1gold100.xyz
	./addPolarizableGold finalStructure_c30d1.lammps05 Au110_cut.lammpstrj c30d1gold110.data c30d1gold110.xyz
	./addPolarizableGold finalStructure_c30d1.lammps05 Au111_cut.lammpstrj c30d1gold111.data c30d1gold111.xyz
	./addPolarizableGold finalStructure_c40d1.lammps05 Au100_cut.lammpstrj c40d1gold100.data c40d1gold100.xyz
	./addPolarizableGold finalStructure_c40d1.lammps05 Au110_cut.lammpstrj c40d1gold110.data c40d1gold110.xyz
	./addPolarizableGold finalStructure_c40d1.lammps05 Au111_cut.lammpstrj c40d1gold111.data c40d1gold111.xyz
	./addPolarizableGold finalStructure_c46d1.lammps05 Au100_cut.lammpstrj c46d1gold100.data c46d1gold100.xyz
	./addPolarizableGold finalStructure_c46d1.lammps05 Au110_cut.lammpstrj c46d1gold110.data c46d1gold110.xyz
	./addPolarizableGold finalStructure_c46d1.lammps05 Au111_cut.lammpstrj c46d1gold111.data c46d1gold111.xyz
run111:
	./addPolarizableGold finalStructure_c5d1.lammps05 Au111_cut.lammpstrj c5d1gold111.data c5d1gold111.xyz
	./addPolarizableGold finalStructure_c10d1.lammps05 Au111_cut.lammpstrj c10d1gold111.data c10d1gold111.xyz
	./addPolarizableGold finalStructure_c15d1.lammps05 Au111_cut.lammpstrj c15d1gold111.data c15d1gold111.xyz
	./addPolarizableGold finalStructure_c20d1.lammps05 Au111_cut.lammpstrj c20d1gold111.data c20d1gold111.xyz
	./addPolarizableGold finalStructure_c25d1.lammps05 Au111_cut.lammpstrj c25d1gold111.data c25d1gold111.xyz
	./addPolarizableGold finalStructure_c30d1.lammps05 Au111_cut.lammpstrj c30d1gold111.data c30d1gold111.xyz
	./addPolarizableGold finalStructure_c40d1.lammps05 Au111_cut.lammpstrj c40d1gold111.data c40d1gold111.xyz
	./addPolarizableGold finalStructure_c46d1.lammps05 Au111_cut.lammpstrj c46d1gold111.data c46d1gold111.xyz
